sudo: required

# Use Travis' Ubuntu Trusty machines. They have more RAM.
# It does not affect which OSs we are testing, since they all provided
# by Docker containers. This simply defines which OS Docker itself will
# be running on.
dist: trusty

services:
  - docker

language: ruby

rvm:
  - 2.3.4

script:
  - docker run --privileged -d polarbearlabs/haveged:1.9.1 # https://github.com/elastic/logstash/issues/5507
  - (if [[ -n $TRAVIS_LINT ]]; then make lint; else bundle exec rake beaker; fi)

env:
  global:
    - LOGSTASH_VERSION=6.0.0
    - BEAKER_PE_DIR=spec/fixtures/artifacts
  matrix:
    # Do linting once.
    - TRAVIS_LINT=true

    # Then run the acceptance tests across the matrix.
    - PUPPET_VERSION=4.6.1 BEAKER_set=centos-6
    - PUPPET_VERSION=4.8.2 BEAKER_set=centos-6
    - PUPPET_VERSION=4.8.2 BEAKER_set=centos-6 LOGSTASH_VERSION=5.6.4

    - PUPPET_VERSION=4.6.1 BEAKER_set=centos-7
    - PUPPET_VERSION=4.7.0 BEAKER_set=centos-7
    - PUPPET_VERSION=4.8.2 BEAKER_set=centos-7
    - PUPPET_VERSION=4.9.4 BEAKER_set=centos-7
    - PUPPET_VERSION=4.10.8 BEAKER_set=centos-7
    - PUPPET_VERSION=4.10.8 BEAKER_set=centos-7 LOGSTASH_VERSION=5.6.4

    - PUPPET_VERSION=5.3.3 BEAKER_set=centos-7
    - PUPPET_VERSION=5.3.3 BEAKER_set=centos-7 LOGSTASH_VERSION=5.6.4

    - PUPPET_VERSION=4.6.1 BEAKER_set=debian-7
    - PUPPET_VERSION=4.8.2 BEAKER_set=debian-7
    - PUPPET_VERSION=4.8.2 BEAKER_set=debian-7 LOGSTASH_VERSION=5.6.4

    - PUPPET_VERSION=4.6.1 BEAKER_set=debian-8
    - PUPPET_VERSION=4.8.2 BEAKER_set=debian-8
    - PUPPET_VERSION=4.9.4 BEAKER_set=debian-8
    - PUPPET_VERSION=4.10.8 BEAKER_set=debian-8
    - PUPPET_VERSION=4.10.8 BEAKER_set=debian-8 LOGSTASH_VERSION=5.6.4

    - PUPPET_VERSION=5.3.3 BEAKER_set=debian-8
    - PUPPET_VERSION=5.3.3 BEAKER_set=debian-8 LOGSTASH_VERSION=5.6.4

    - PUPPET_VERSION=4.6.1 BEAKER_set=ubuntu-1404
    - PUPPET_VERSION=4.8.2 BEAKER_set=ubuntu-1404
    - PUPPET_VERSION=4.9.4 BEAKER_set=ubuntu-1404
    - PUPPET_VERSION=4.10.8 BEAKER_set=ubuntu-1404
    - PUPPET_VERSION=4.10.8 BEAKER_set=ubuntu-1404 LOGSTASH_VERSION=5.6.4

    - PUPPET_VERSION=5.3.3 BEAKER_set=ubuntu-1404
    - PUPPET_VERSION=5.3.3 BEAKER_set=ubuntu-1404 LOGSTASH_VERSION=5.6.4

    - PUPPET_VERSION=4.6.1 BEAKER_set=ubuntu-1604
    - PUPPET_VERSION=4.8.2 BEAKER_set=ubuntu-1604
    - PUPPET_VERSION=4.9.4 BEAKER_set=ubuntu-1604
    - PUPPET_VERSION=4.10.8 BEAKER_set=ubuntu-1604
    - PUPPET_VERSION=4.10.8 BEAKER_set=ubuntu-1604 LOGSTASH_VERSION=5.6.4

    - PUPPET_VERSION=5.0.1 BEAKER_set=ubuntu-1604
    - PUPPET_VERSION=5.1.0 BEAKER_set=ubuntu-1604
    - PUPPET_VERSION=5.2.0 BEAKER_set=ubuntu-1604
    - PUPPET_VERSION=5.3.3 BEAKER_set=ubuntu-1604
    - PUPPET_VERSION=5.3.3 BEAKER_set=ubuntu-1604 LOGSTASH_VERSION=5.6.4
